### PR TITLE
bug fix for the example

### PR DESCRIPTION
**Pull request by liupibm**
### Summary
This PR is requested for fixing a bug in using_sympy_provider_level_1.py.

instead of using:
unitary_job = unitary_backend.run(qobj) 
we shall use:
qobj2 = compile([qc1, qc2], backend=unitary_backend) 
unitary_job = unitary_backend.run(qobj2)

the previous code can lead to the following validation exception. 
The reason is that unitary_backend was used to run the qobj that specifies statevector_backend as the backend.

### Details and comments

Traceback (most recent call last):
  File "/Users/liup/quantum/qiskit-sympy-provider/examples/using_sympy_provider_level_1.py", line 55, in <module>
    unitary_job = unitary_backend.run(qobj)
  File "/Users/liup/quantum/qiskit-sympy-provider/qiskit_addon_sympy/unitary_simulator.py", line 183, in run
    sym_job.submit()
  File "/Users/liup/quantum/qiskit-sympy-provider/qiskit_addon_sympy/sympyjob.py", line 70, in submit
    validate_qobj_against_schema(self._qobj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qiskit/qobj/_validation.py", line 22, in validate_qobj_against_schema
    err_msg='Qobj failed validation. '
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qiskit/_schema_validation.py", line 149, in validate_json_against_schema
    raise newerr
qiskit._schema_validation.SchemaValidationError: 'Qobj failed validation. Set Qiskit log level to DEBUG for further information.'

Process finished with exit code 1

### CODE REVIEW

**Comment by liupibm** [comment]
hi @yaelbh , could you have a look at the PR, thanks!

**Comment by jaygambetta** [comment]
This is the point of the compile once use twice. How are you getting this bug

**Comment by yaelbh** [comment]
The intention is to show to the user that it is possible to compile only once, in a compilation targeted to one of the simulators, and then run both simulators on the same qobj. Whereas the beginner user at level 0 calls ``execute`` twice, hence compiling twice, where each compilation is targeted to another simulator.

In general a simulator can indeed fail when executed on qobj that was compiled for another simulator. But specifically for the case of the two Sympy simulators I don't see how this can happen. Did you run exactly the example, of changed in the input circuit? If changed, then to which circuit?

**Comment by liupibm** [comment]
@yaelbh I did not make any change. 
after downloading this repo, then I run the example without changes.
my qiskit is installed with "pip3 install qiskit --user".
the qiskit version is 0.6.1.
seems the error is thrown from the qiskit.

**Comment by yaelbh** [comment]
I fail to reproduce the bug.
I see that you are using Qiskit which is located in your machine at:
``/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qiskit``
Are you sure that this is the Qiskit version that you've just installed?
It could be that Qiskit has been installed elsewhere, whereas the version in ``/Library/Frameworks`` is an old one.
In my machine, ``pip`` and ``pip3`` install in different locations, where ``pip`` is the "correct" one, in the sense that ``pip`` installs in the default path of Python.
Could you please check what happens if you use ``pip`` instead of ``pip3``?

**Comment by liupibm** [comment]
@yaelbh after i reinstalled qiskit, everything works now. Thanks.

**Pull request closed without merging**
